print("    __________")
print("    |         |")
print("    |         |")
print("    0         |")
print("   /|\\        |")
print("    |         |")
print("   / \\        |")
print("              |")
print("              |")
print("      ________|")
